# Generated by Django 4.2.4 on 2023-09-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("phonenumber", models.CharField(max_length=10)),
                ("discount", models.FloatField()),
                ("creditlimit", models.DecimalField(decimal_places=1, max_digits=5)),
                ("tinnumber", models.BigIntegerField()),
                ("vrnnumber", models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Customers",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="a_s_value",
        ),
        migrations.AddField(
            model_name="purchase",
            name="discount",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="best_selling_product",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("beverage", "Beverage"),
                    ("household", "Household"),
                    ("other", "Other"),
                ],
                default="food",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="stock_available_value",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="uom",
            field=models.CharField(
                choices=[
                    ("pcs", "Pieces"),
                    ("kg", "Kilograms"),
                    ("m", "Meters"),
                    ("L", "Liters"),
                    ("lbs", "Pounds"),
                    ("gal", "Gallons"),
                ],
                default="kg",
                max_length=255,
            ),
        ),
    ]
