# Generated by Django 4.2.4 on 2023-09-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="reorder_point",
            field=models.BigIntegerField(default=50),
        ),
    ]
