# Generated by Django 4.2.4 on 2023-09-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_customer_creditlimit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="stock_available_value",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="total_purchases",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="total_sales",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="discount",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="total",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="unit_price",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
