# Generated by Django 4.2.4 on 2023-09-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_inventory_reorder_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("beverage", "Beverage"),
                    ("household", "Household"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=255,
            ),
        ),
    ]
