# Generated by Django 4.2.4 on 2023-09-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_inventory_stock_available_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="creditlimit",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total_amount",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="sale",
            name="unit_price",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
